'use strict';
// ============================================================
// 仙劍天下 - WORLD DATA EXPANSION
// New Regions, Dungeons, NPCs, Quests, Bosses, Elites, Lore
// ============================================================

const WorldData = {

  // ============================================================
  // REGIONS
  // ============================================================
  regions: [
    {
      id: 'starting_village',
      name: '青雲村',
      nameEn: 'Azure Cloud Village',
      type: 'village',
      icon: '🏡',
      levelRange: [1, 10],
      description: '世界的起點，寧靜的仙家小村。',
      lore: '相傳此地乃上古仙人結界所護，千年未有妖邪侵擾。村中有一口古井，據說能聽見先人的低語……',
      music: 'village_theme',
      weather: 'clear',
      spawnX: 512, spawnY: 512,
      locked: false,
      ambientColor: 'rgba(40,80,20,0.08)',
      monsters: ['妖狐', '幽靈武士'],
      eliteMonsters: ['白狐族長'],
      boss: null,
      npcs: ['village_elder', 'blacksmith_wang', 'merchant_li', 'quest_giver_chen'],
      quests: ['q_first_steps', 'q_wolf_menace', 'q_lost_herb'],
      fog: false,
      dungeonEntrance: null,
    },
    {
      id: 'jade_forest',
      name: '翠玉仙境',
      nameEn: 'Jade Immortal Realm',
      type: 'forest',
      icon: '🌿',
      levelRange: [10, 25],
      description: '古老翠竹密林，靈氣濃鬱，妖獸橫行。',
      lore: '翠玉仙境曾是上古修仙者的靜修之地。如今靈脈受損，各路妖獸紛紛佔據此地，昔日的仙家洞府早已滿目瘡痍……',
      music: 'forest_theme',
      weather: 'misty',
      spawnX: 1400, spawnY: 600,
      locked: false,
      ambientColor: 'rgba(20,80,20,0.12)',
      monsters: ['妖狐', '幽靈武士', '火精靈'],
      eliteMonsters: ['幽影劍士', '翠竹妖王'],
      boss: 'boss_jade_serpent',
      npcs: ['hermit_zhang', 'forest_guard'],
      quests: ['q_forest_curse', 'q_jade_fragment', 'q_serpent_slayer'],
      fog: true,
      dungeonEntrance: 'dungeon_bamboo_temple',
    },
    {
      id: 'iron_mountain',
      name: '玄鐵山脈',
      nameEn: 'Black Iron Mountains',
      type: 'mountain',
      icon: '⛰️',
      levelRange: [25, 40],
      description: '崇山峻嶺，蘊藏稀世礦脈，危機四伏。',
      lore: '玄鐵山脈以產稀有靈礦著稱。深山之中住著石魔族群，它們守護著一座封印著遠古魔物的地下神殿……',
      music: 'mountain_theme',
      weather: 'overcast',
      spawnX: 2400, spawnY: 800,
      locked: false,
      ambientColor: 'rgba(60,50,30,0.15)',
      monsters: ['石魔', '幽靈武士'],
      eliteMonsters: ['玄鐵巨魔', '山嶽靈獸'],
      boss: 'boss_iron_titan',
      npcs: ['miner_foreman', 'dwarven_smith'],
      quests: ['q_ore_crisis', 'q_titan_hunt', 'q_ancient_seal'],
      fog: false,
      dungeonEntrance: 'dungeon_iron_depths',
    },
    {
      id: 'ghost_ruins',
      name: '幽冥古城',
      nameEn: 'Ghost Ancient City',
      type: 'ruins',
      icon: '🏚️',
      levelRange: [40, 55],
      description: '千年廢墟，陰氣沖天，亡靈不散。',
      lore: '此城昔日繁華，卻因修羅血煞大陣而毀於一夜。城中百姓的怨靈千年難散，等待勇者前來超度……',
      music: 'ghost_theme',
      weather: 'stormy',
      spawnX: 3200, spawnY: 1200,
      locked: false,
      ambientColor: 'rgba(60,0,80,0.18)',
      monsters: ['幽靈武士', '石魔'],
      eliteMonsters: ['陰靈將軍', '屍王術士'],
      boss: 'boss_lich_king',
      npcs: ['spirit_medium', 'wandering_priest'],
      quests: ['q_soul_release', 'q_cursed_sword', 'q_lich_bane'],
      fog: true,
      dungeonEntrance: 'dungeon_netherworld',
    },
    {
      id: 'heavenly_peak',
      name: '天極仙山',
      nameEn: 'Heavenly Peak',
      type: 'mountain',
      icon: '🗻',
      levelRange: [55, 70],
      description: '通天之巔，雲霧繚繞，仙家聖地。',
      lore: '天極仙山乃三界結界交匯之處，上古時代仙魔之戰的最終決戰場。山頂封印著魔祖的碎片，守護者已失去聯繫……',
      music: 'heaven_theme',
      weather: 'celestial',
      spawnX: 4000, spawnY: 400,
      locked: true,
      ambientColor: 'rgba(100,80,200,0.15)',
      monsters: ['火精靈', '幽靈武士'],
      eliteMonsters: ['天雷神獸', '仙門衛士'],
      boss: 'boss_demon_ancestor',
      npcs: ['celestial_guardian', 'ancient_immortal'],
      quests: ['q_ascend_peak', 'q_broken_seal', 'q_demon_fragment'],
      fog: false,
      dungeonEntrance: 'dungeon_celestial_vault',
    },
    {
      id: 'blood_swamp',
      name: '血色沼澤',
      nameEn: 'Crimson Swamp',
      type: 'swamp',
      icon: '🌫️',
      levelRange: [30, 45],
      description: '赤紅沼澤，毒瘴瀰漫，邪祟橫行。',
      lore: '古代一場大戰讓千萬仙兵的鮮血染紅了這片土地。血煞之氣百年未散，催生了無數嗜血邪獸……',
      music: 'swamp_theme',
      weather: 'toxic',
      spawnX: 1800, spawnY: 1800,
      locked: false,
      ambientColor: 'rgba(120,20,20,0.18)',
      monsters: ['妖狐', '火精靈', '石魔'],
      eliteMonsters: ['血蛟魔君', '赤蠍刺客'],
      boss: 'boss_blood_drake',
      npcs: ['plague_doctor', 'lost_adventurer'],
      quests: ['q_swamp_cure', 'q_blood_lotus', 'q_drake_scale'],
      fog: true,
      dungeonEntrance: 'dungeon_sunken_temple',
    },
    {
      id: 'sect_headquarters',
      name: '青劍宗',
      nameEn: 'Azure Sword Sect',
      type: 'sect',
      icon: '⚔️',
      levelRange: [15, 99],
      description: '天下第一劍宗，英雄輩出之地。',
      lore: '青劍宗立派千年，以劍道正宗自居。歷代掌門皆是絕世高手。如今宗門遭受內憂外患，急需可靠弟子協助……',
      music: 'sect_theme',
      weather: 'clear',
      spawnX: 2800, spawnY: 400,
      locked: false,
      ambientColor: 'rgba(20,60,120,0.10)',
      monsters: [],
      eliteMonsters: [],
      boss: null,
      npcs: ['sect_master', 'inner_elder', 'sect_steward', 'training_instructor'],
      quests: ['q_join_sect', 'q_inner_disciple', 'q_sect_mission'],
      fog: false,
      dungeonEntrance: null,
    },
  ],

  // ============================================================
  // DUNGEONS
  // ============================================================
  dungeons: [
    {
      id: 'dungeon_bamboo_temple',
      name: '翠竹祕境',
      nameEn: 'Bamboo Secret Temple',
      icon: '🎋',
      regionId: 'jade_forest',
      levelReq: 12,
      floors: 3,
      description: '幽深的竹林古廟，封印破碎，妖氣外溢。',
      lore: '這座古廟建於仙紀元年，是修仙者們用來供奉翠竹仙靈的聖地。如今仙靈已化為厲鬼，等待著解脫……',
      boss: 'boss_jade_serpent',
      eliteGuards: ['幽影劍士', '竹林毒蟲精'],
      rewards: ['翡翠玲瓏衣', '竹節長劍', '仙靈露×5'],
      ambientLight: 'rgba(20,80,20,0.3)',
      mapStyle: 'dungeon_bamboo',
      entranceX: 1600, entranceY: 700,
    },
    {
      id: 'dungeon_iron_depths',
      name: '玄鐵秘窟',
      nameEn: 'Iron Secret Cavern',
      icon: '⛏️',
      regionId: 'iron_mountain',
      levelReq: 28,
      floors: 4,
      description: '幽暗礦窟，深入地底，古神兵器沉睡其中。',
      lore: '礦窟最深處供奉著上古戰神遺留的神兵——「玄鐵破天戟」，無數盜墓賊為此葬身其中……',
      boss: 'boss_iron_titan',
      eliteGuards: ['玄鐵巨魔', '深淵石爪'],
      rewards: ['玄鐵重甲', '破天長戟', '隕鐵原石×10'],
      ambientLight: 'rgba(60,40,10,0.3)',
      mapStyle: 'dungeon_cave',
      entranceX: 2600, entranceY: 900,
    },
    {
      id: 'dungeon_netherworld',
      name: '冥府幽城',
      nameEn: 'Netherworld Ghost City',
      icon: '💀',
      regionId: 'ghost_ruins',
      levelReq: 42,
      floors: 5,
      description: '通往冥界的入口，亡靈與鬼差雜居之地。',
      lore: '古城地下隱藏著一條通往真正冥界的通道。傳說其中有著冥王的封印——只要打破它，便能召喚萬魂大軍……',
      boss: 'boss_lich_king',
      eliteGuards: ['陰靈將軍', '冥府護法'],
      rewards: ['幽冥靈甲', '判官巨筆', '亡靈核心×3'],
      ambientLight: 'rgba(60,0,80,0.35)',
      mapStyle: 'dungeon_ghost',
      entranceX: 3400, entranceY: 1300,
    },
    {
      id: 'dungeon_celestial_vault',
      name: '天穹封印地',
      nameEn: 'Celestial Vault',
      icon: '✨',
      regionId: 'heavenly_peak',
      levelReq: 58,
      floors: 6,
      description: '天極仙山深處的封印地，魔祖碎片長眠於此。',
      lore: '萬年前仙魔大戰的終結之地。十二位仙尊聯手以生命為代價，將魔祖封印於此。封印正在一點點崩解……',
      boss: 'boss_demon_ancestor',
      eliteGuards: ['天雷神獸', '破封魔將'],
      rewards: ['仙尊遺甲', '封魔神劍', '魔祖碎片'],
      ambientLight: 'rgba(80,60,200,0.3)',
      mapStyle: 'dungeon_celestial',
      entranceX: 4200, entranceY: 500,
    },
    {
      id: 'dungeon_sunken_temple',
      name: '沉沒血祠',
      nameEn: 'Sunken Blood Shrine',
      icon: '🩸',
      regionId: 'blood_swamp',
      levelReq: 33,
      floors: 4,
      description: '沉入沼澤深處的古祠，血蛟魔君的巢穴。',
      lore: '古血祠是遠古邪教祭祀血神的場所。祭祀儀式引發了血脈共鳴，讓沼澤中的所有生物都陷入了瘋狂……',
      boss: 'boss_blood_drake',
      eliteGuards: ['血蛟魔君', '赤蠍刺客'],
      rewards: ['血龍鱗甲', '毒蠍雙刃', '腥紅魔晶×5'],
      ambientLight: 'rgba(120,10,10,0.35)',
      mapStyle: 'dungeon_blood',
      entranceX: 2000, entranceY: 1900,
    },
  ],

  // ============================================================
  // BOSSES
  // ============================================================
  bosses: [
    {
      id: 'boss_jade_serpent',
      name: '翠玉蛟王',
      title: '翠竹仙境的守護者',
      level: 20,
      hp: 180000,
      maxHp: 180000,
      atk: 3500,
      def: 800,
      spd: 1.5,
      emoji: '🐍',
      color: { body: '#1a8040', accent: '#40e080', eyes: '#ffee00' },
      size: 2.5,
      skills: [
        { name: '翠毒噴射', type: 'poison_breath', range: 200, damage: 4000, cd: 8 },
        { name: '纏繞碾壓', type: 'constrict', range: 80, damage: 6000, cd: 12 },
        { name: '翠竹召喚', type: 'summon', count: 4, cd: 20 },
      ],
      lore: '昔日守護翠竹仙境的神靈，因仙靈之氣枯竭而瘋狂，化身為噬靈蛟龍……',
      dropTable: [
        { item: '翡翠玲瓏衣', chance: 0.15, rarity: 'epic' },
        { item: '竹節長劍', chance: 0.20, rarity: 'rare' },
        { item: '蛟王之鱗', chance: 0.35, rarity: 'uncommon' },
        { item: '靈玉碎片', chance: 0.80, rarity: 'common' },
        { item: '金幣', amount: [5000, 12000], chance: 1.0 },
      ],
      phaseThreshold: 0.4,
      phase2Name: '狂化翠玉蛟王',
      phase2Skills: ['翠毒爆炸', '千蛇衝刺'],
      position: { x: 1700, y: 650 },
      respawnTimer: 1800,
    },
    {
      id: 'boss_iron_titan',
      name: '玄鐵巨神',
      title: '山嶽的意志',
      level: 35,
      hp: 350000,
      maxHp: 350000,
      atk: 6500,
      def: 2000,
      spd: 0.8,
      emoji: '🗿',
      color: { body: '#505040', accent: '#909070', eyes: '#ff8000' },
      size: 3.5,
      skills: [
        { name: '山崩地裂', type: 'quake', range: 250, damage: 8000, cd: 10 },
        { name: '玄鐵投擲', type: 'projectile', range: 350, damage: 5000, cd: 6 },
        { name: '岩石護甲', type: 'shield', value: 0.5, cd: 30 },
        { name: '地底衝擊', type: 'shockwave', range: 300, damage: 7000, cd: 15 },
      ],
      lore: '玄鐵山脈的守護神靈，億萬年的地氣積累賦予了它接近不朽的軀體。傳說擊敗它能獲得山脈的賜福……',
      dropTable: [
        { item: '玄鐵重甲', chance: 0.12, rarity: 'epic' },
        { item: '破天長戟', chance: 0.12, rarity: 'epic' },
        { item: '巨神之心', chance: 0.25, rarity: 'rare' },
        { item: '玄鐵礦石', amount: [20, 50], chance: 1.0, rarity: 'common' },
        { item: '金幣', amount: [12000, 25000], chance: 1.0 },
      ],
      phaseThreshold: 0.3,
      phase2Name: '覺醒玄鐵巨神',
      phase2Skills: ['熔岩噴湧', '泰山壓頂'],
      position: { x: 2700, y: 850 },
      respawnTimer: 2400,
    },
    {
      id: 'boss_lich_king',
      name: '幽冥魔君',
      title: '千年死靈之主',
      level: 48,
      hp: 520000,
      maxHp: 520000,
      atk: 9000,
      def: 1500,
      spd: 1.2,
      emoji: '💀',
      color: { body: '#303060', accent: '#6060c0', eyes: '#cc00ff' },
      size: 2.8,
      skills: [
        { name: '亡靈軍團', type: 'summon', count: 6, cd: 25 },
        { name: '死靈詛咒', type: 'curse', debuff: 'weaken', duration: 12, cd: 18 },
        { name: '冥冰衝擊', type: 'ice_nova', range: 180, damage: 10000, cd: 12 },
        { name: '吸魂絕殺', type: 'life_drain', range: 100, damage: 12000, cd: 20 },
        { name: '幽冥壁壘', type: 'barrier', cd: 40 },
      ],
      lore: '曾是一位偉大的術士，窮盡一生研究長生術。最終以自身魂魄化作死靈，在幽冥古城中等待了千年……',
      dropTable: [
        { item: '幽冥靈甲', chance: 0.10, rarity: 'legendary' },
        { item: '判官巨筆', chance: 0.10, rarity: 'legendary' },
        { item: '死靈法典', chance: 0.20, rarity: 'epic' },
        { item: '亡靈核心', chance: 0.40, rarity: 'rare' },
        { item: '金幣', amount: [25000, 50000], chance: 1.0 },
      ],
      phaseThreshold: 0.25,
      phase2Name: '真身幽冥魔君',
      phase2Skills: ['滅世冥火', '萬鬼朝天'],
      position: { x: 3500, y: 1250 },
      respawnTimer: 3600,
    },
    {
      id: 'boss_blood_drake',
      name: '血蛟天魔',
      title: '沼澤深處的血神使者',
      level: 40,
      hp: 420000,
      maxHp: 420000,
      atk: 7500,
      def: 1200,
      spd: 1.8,
      emoji: '🐉',
      color: { body: '#800020', accent: '#ff4040', eyes: '#ff0000' },
      size: 3.0,
      skills: [
        { name: '血雨腥風', type: 'aoe_bleed', range: 200, damage: 6000, cd: 10 },
        { name: '毒血噴吐', type: 'poison_spit', range: 250, damage: 8000, cd: 15 },
        { name: '血翼橫掃', type: 'wing_sweep', range: 160, damage: 9000, cd: 12 },
        { name: '鮮血狂化', type: 'berserk', threshold: 0.5, atkBonus: 1.5, cd: 0 },
      ],
      lore: '古血祠血神的化身，以億萬亡魂的怨念凝聚而成。它沉睡在沼澤最深處，嗜血的本能讓它難以停止殺戮……',
      dropTable: [
        { item: '血龍鱗甲', chance: 0.12, rarity: 'epic' },
        { item: '毒蠍雙刃', chance: 0.15, rarity: 'rare' },
        { item: '腥紅魔晶', chance: 0.35, rarity: 'uncommon' },
        { item: '血祠神紋', chance: 0.08, rarity: 'legendary' },
        { item: '金幣', amount: [18000, 35000], chance: 1.0 },
      ],
      phaseThreshold: 0.35,
      phase2Name: '血煞狂化血蛟天魔',
      phase2Skills: ['血色末日', '九頭噬靈'],
      position: { x: 2100, y: 1850 },
      respawnTimer: 2700,
    },
    {
      id: 'boss_demon_ancestor',
      name: '魔祖降世',
      title: '萬古魔道之源',
      level: 65,
      hp: 1000000,
      maxHp: 1000000,
      atk: 15000,
      def: 3000,
      spd: 1.0,
      emoji: '👹',
      color: { body: '#400040', accent: '#cc00cc', eyes: '#ff00ff' },
      size: 4.5,
      skills: [
        { name: '萬魔降世', type: 'mega_summon', count: 8, cd: 30 },
        { name: '魔道玄火', type: 'demonic_fire', range: 300, damage: 20000, cd: 8 },
        { name: '心魔侵蝕', type: 'mind_break', debuff: 'confuse', duration: 6, cd: 20 },
        { name: '魔祖天威', type: 'terror_aura', range: 400, cd: 0 },
        { name: '虛空裂縫', type: 'void_rift', damage: 25000, cd: 25 },
        { name: '魔道輪迴', type: 'revive', hpRestore: 0.3, count: 1, cd: 0 },
      ],
      lore: '萬年前被十二仙尊封印的原初魔祖。它並非邪惡，而是秩序的對立面——混沌之源。封印破裂，它帶著對這個世界無盡的怒火歸來……',
      dropTable: [
        { item: '魔祖真炎', chance: 0.05, rarity: 'legendary' },
        { item: '仙尊遺甲', chance: 0.05, rarity: 'legendary' },
        { item: '封魔神劍', chance: 0.05, rarity: 'legendary' },
        { item: '混沌靈核', chance: 0.15, rarity: 'epic' },
        { item: '金幣', amount: [100000, 200000], chance: 1.0 },
        { item: '魔祖碎片', chance: 0.60, rarity: 'epic' },
      ],
      phaseThreshold: 0.5,
      phase2Name: '魔祖本體覺醒',
      phase2Skills: ['混沌毀滅', '時空逆流', '萬魔帝陣'],
      position: { x: 4300, y: 450 },
      respawnTimer: 7200,
    },
  ],

  // ============================================================
  // ELITE MONSTERS
  // ============================================================
  elites: [
    {
      id: 'elite_white_fox',
      name: '白狐族長',
      baseType: '妖狐',
      level: 8,
      hpMultiplier: 5,
      atkMultiplier: 2.5,
      emoji: '🦊',
      color: { body: '#ffffff', tail: '#ffcccc', eyes: '#ff2040' },
      skills: ['魅惑', '幻影分身'],
      lore: '白狐族的首領，擁有千年道行，能以美麗的幻象迷惑入侵者。',
      dropBonus: ['狐妖靈珠', '銀毫幻裳'],
      spawnWeight: 0.08,
    },
    {
      id: 'elite_phantom_swordsman',
      name: '幽影劍士',
      baseType: '幽靈武士',
      level: 18,
      hpMultiplier: 6,
      atkMultiplier: 3.0,
      emoji: '⚔️',
      color: { body: '#2a3060', tail: '#6080e0', eyes: '#80c0ff' },
      skills: ['幻影斬', '靈劍雨', '鬼步閃移'],
      lore: '戰死沙場的絕世劍客，執念未消，化為幽影繼續守護其主人留下的寶物。',
      dropBonus: ['幽影長劍', '鬼武士盔'],
      spawnWeight: 0.06,
    },
    {
      id: 'elite_jade_demon',
      name: '翠竹妖王',
      baseType: '妖狐',
      level: 22,
      hpMultiplier: 7,
      atkMultiplier: 2.8,
      emoji: '🎋',
      color: { body: '#204020', tail: '#40a040', eyes: '#80ff40' },
      skills: ['翠竹束縛', '竹刺風暴'],
      lore: '千年竹精化形，以翠竹仙境為家，對外來者充滿敵意。',
      dropBonus: ['翠竹靈符', '竹節護腕'],
      spawnWeight: 0.07,
    },
    {
      id: 'elite_iron_golem',
      name: '玄鐵巨魔',
      baseType: '石魔',
      level: 32,
      hpMultiplier: 8,
      atkMultiplier: 2.5,
      emoji: '🗿',
      color: { body: '#404030', tail: '#808060', eyes: '#ff8000' },
      skills: ['鐵拳碾壓', '岩石投擲', '大地震顫'],
      lore: '以玄鐵礦石凝聚而成的古老守衛，每次擊殺敵人都會讓它的身體更加堅硬。',
      dropBonus: ['玄鐵礦石', '巨魔石核'],
      spawnWeight: 0.06,
    },
    {
      id: 'elite_mountain_beast',
      name: '山嶽靈獸',
      baseType: '石魔',
      level: 36,
      hpMultiplier: 6,
      atkMultiplier: 3.5,
      emoji: '🦁',
      color: { body: '#806040', tail: '#c09060', eyes: '#ffcc00' },
      skills: ['山嶽之怒', '岩爪撕裂', '獸魂咆哮'],
      lore: '山脈靈氣孕育的神獸，傳說見到它意味著山神在考驗凡人的勇氣。',
      dropBonus: ['靈獸毛皮', '山神牙飾'],
      spawnWeight: 0.05,
    },
    {
      id: 'elite_spirit_general',
      name: '陰靈將軍',
      baseType: '幽靈武士',
      level: 45,
      hpMultiplier: 8,
      atkMultiplier: 3.2,
      emoji: '👻',
      color: { body: '#303050', tail: '#5050a0', eyes: '#ff00cc' },
      skills: ['陰靈大軍', '鬼斬迴旋', '死者詛咒'],
      lore: '幽冥古城最後的守衛將軍，帶著未能保護城中百姓的悔恨，永遠在廢墟中巡邏。',
      dropBonus: ['冥將盔甲', '陰兵令牌'],
      spawnWeight: 0.06,
    },
    {
      id: 'elite_corpse_mage',
      name: '屍王術士',
      baseType: '幽靈武士',
      level: 48,
      hpMultiplier: 5,
      atkMultiplier: 4.0,
      emoji: '🧟',
      color: { body: '#304030', tail: '#608060', eyes: '#00ff80' },
      skills: ['屍毒術', '腐爛波動', '亡靈複生'],
      lore: '一位沉迷於禁忌魔法的術士，以自身的死亡作為最終實驗材料，達到了前所未有的強度。',
      dropBonus: ['禁忌術典', '屍毒精華'],
      spawnWeight: 0.05,
    },
    {
      id: 'elite_thunder_beast',
      name: '天雷神獸',
      baseType: '火精靈',
      level: 60,
      hpMultiplier: 9,
      atkMultiplier: 4.5,
      emoji: '⚡',
      color: { body: '#404080', tail: '#8080ff', eyes: '#ffff00' },
      skills: ['雷霆萬鈞', '電光縛鎖', '天雷審判'],
      lore: '天極仙山的鎮山神獸，以天雷之力守護仙山封印。只有真正的勇者才能在它面前存活。',
      dropBonus: ['天雷神晶', '雷獸之心'],
      spawnWeight: 0.04,
    },
    {
      id: 'elite_blood_scorpion',
      name: '赤蠍刺客',
      baseType: '妖狐',
      level: 38,
      hpMultiplier: 5,
      atkMultiplier: 5.0,
      emoji: '🦂',
      color: { body: '#800010', tail: '#ff4020', eyes: '#ff0000' },
      skills: ['劇毒刺針', '血霧隱形', '致命暗刺'],
      lore: '血色沼澤中最危險的刺客，能以毒針在瞬間終結對手的生命。江湖上流傳著「見赤蠍者，無一生還」的傳說。',
      dropBonus: ['赤蠍毒液', '暗刺短匕'],
      spawnWeight: 0.07,
    },
    {
      id: 'elite_blood_flood_dragon',
      name: '血蛟魔君',
      baseType: '火精靈',
      level: 42,
      hpMultiplier: 10,
      atkMultiplier: 3.5,
      emoji: '🐲',
      color: { body: '#600010', tail: '#cc2020', eyes: '#ff6000' },
      skills: ['血洪漫卷', '蛟龍噬咬', '邪血濺射'],
      lore: '血色沼澤的霸主，傳說它是上古凶龍的血裔。見血即狂，殺戮不止。',
      dropBonus: ['蛟龍血晶', '魔龍牙'],
      spawnWeight: 0.05,
    },
  ],

  // ============================================================
  // NPCs
  // ============================================================
  npcs: [
    {
      id: 'village_elder',
      name: '青雲長老',
      role: '村中德高望重的長老',
      emoji: '👴',
      type: 'quest_giver',
      regionId: 'starting_village',
      x: 480, y: 460,
      quests: ['q_first_steps', 'q_wolf_menace'],
      dialog: {
        greeting: '年輕人，你來得正是時候。村子近日妖獸橫行，我等需要你的幫助！',
        quest_hint: '若要強大，先從擊殺附近的妖狐開始。打敗它們，為村民們掙一份安寧。',
        after_quest: '做得好！你真是個有為的年輕人。未來的路還很長，繼續努力吧！',
        lore: '這青雲村已有三千年歷史。相傳村子建在一處靈脈之上，這也是為何妖獸對此地如此垂涎……',
      },
      merchandise: [],
    },
    {
      id: 'blacksmith_wang',
      name: '鐵匠王老爺',
      role: '技藝精湛的武器鐵匠',
      emoji: '🔨',
      type: 'blacksmith',
      regionId: 'starting_village',
      x: 540, y: 490,
      quests: [],
      dialog: {
        greeting: '需要打造武器？老夫這裡什麼都能打！你帶材料來，老夫不收工錢！',
        shop_prompt: '看看我最新的鍛造品，保你上陣殺敵如虎添翼！',
        after_quest: '帶著好武器去吧，在外面記得保重！',
        lore: '老夫的師父說，最好的武器是用心打造的。每一把劍，都凝聚著鑄劍者的魂……',
      },
      merchandise: [
        { name: '精鐵長劍', price: 500, type: 'weapon', icon: '⚔️', rarity: 'uncommon' },
        { name: '鋼盾', price: 400, type: 'armor', icon: '🛡️', rarity: 'uncommon' },
        { name: '強化石×3', price: 200, type: 'material', icon: '💎', rarity: 'common' },
      ],
    },
    {
      id: 'merchant_li',
      name: '商人李四海',
      role: '走南闖北的行商',
      emoji: '💰',
      type: 'merchant',
      regionId: 'starting_village',
      x: 500, y: 520,
      quests: [],
      dialog: {
        greeting: '客官，您眼光真好！老夫這裡有天南地北搜羅來的稀罕物，保您滿意！',
        shop_prompt: '仙丹靈藥、奇珍異寶，樣樣俱全！',
        after_quest: '歡迎再來！老夫在這裡等您！',
        lore: '老夫年輕時走遍了七州八府，見過無數奇人異士。江湖上最值錢的，不是金銀，而是情報……',
      },
      merchandise: [
        { name: '回血丹×5', price: 150, type: 'consumable', icon: '💊', rarity: 'common' },
        { name: '回靈丹×5', price: 150, type: 'consumable', icon: '🔮', rarity: 'common' },
        { name: '傳送符×3', price: 300, type: 'consumable', icon: '📜', rarity: 'uncommon' },
        { name: '靈石×10', price: 500, type: 'currency', icon: '🔷', rarity: 'common' },
      ],
    },
    {
      id: 'quest_giver_chen',
      name: '陳英雄',
      role: '退役老兵，壯志未酬',
      emoji: '🪖',
      type: 'quest_giver',
      regionId: 'starting_village',
      x: 450, y: 510,
      quests: ['q_lost_herb'],
      dialog: {
        greeting: '老夫雖老，但這身武藝還在！你來找我，必是聽說了那片草藥林的事……',
        quest_hint: '那草藥叫「千年雪蓮」，能救活無數村民。可惜林子裡妖獸太多，老夫一人擋不住……',
        after_quest: '哈哈！好樣的！不愧是老夫看好的年輕人！',
        lore: '老夫年輕時也是威震一方的英雄。後來在玄鐵山脈受了重傷，只好在此頤養天年。不過那段往事……算了，不說了。',
      },
      merchandise: [],
    },
    {
      id: 'hermit_zhang',
      name: '隱士張無為',
      role: '隱居仙境的得道高人',
      emoji: '🧙',
      type: 'quest_giver',
      regionId: 'jade_forest',
      x: 1350, y: 580,
      quests: ['q_forest_curse', 'q_jade_fragment'],
      dialog: {
        greeting: '（閉目打坐中，緩緩睜眼）……你的到來，早在老夫預料之中。翠竹仙境正遭受詛咒，仙靈在哭泣。',
        quest_hint: '想要解除詛咒，需要收集三塊「翠玉靈晶」。它們分散在仙境各處，被蛟王的手下守護……',
        after_quest: '大道無形，造化無常。你已踏上了修行的正道，繼續前行吧，年輕人。',
        lore: '老夫曾是青劍宗的首席弟子，卻在一次修煉失誤後走火入魔，在此隱居三十年才重拾修道之心……',
      },
      merchandise: [],
    },
    {
      id: 'forest_guard',
      name: '林間衛士燕青',
      role: '翠玉仙境的守衛隊長',
      emoji: '💂',
      type: 'guard',
      regionId: 'jade_forest',
      x: 1450, y: 620,
      quests: ['q_serpent_slayer'],
      dialog: {
        greeting: '站住！不知道前面有多危險嗎？……等等，你是來討伐蛟王的？那正好，我有個任務要拜託你。',
        quest_hint: '蛟王身上有一塊「靈晶核心」，帶回來給我，你會得到豐厚的獎勵。',
        after_quest: '你真的做到了！我從未見過如此勇猛的戰士……請收下這份禮物，是我個人的心意。',
        lore: '我已在這裡守衛十年了。仙境從未如此兇險過。希望你能找到根源，拯救這片土地……',
      },
      merchandise: [],
    },
    {
      id: 'miner_foreman',
      name: '礦工頭領周猛',
      role: '玄鐵山礦場的工頭',
      emoji: '⛏️',
      type: 'quest_giver',
      regionId: 'iron_mountain',
      x: 2380, y: 790,
      quests: ['q_ore_crisis'],
      dialog: {
        greeting: '老天爺！你從外面來的？太好了！最近石魔族發狂，把我們的礦工都趕出來了，礦場停工半個月了！',
        quest_hint: '如果你能清除礦場裡的石魔，再帶回來一批玄鐵礦石……老夫重謝你！',
        after_quest: '兄弟，你救了我們所有人！這份恩情，我礦工周猛永遠記著！',
        lore: '玄鐵山的礦石乃是天下頂尖的鍛造材料。傳說最深處有「星隕鐵」，用它打造的武器可以斬仙殺佛。',
      },
      merchandise: [],
    },
    {
      id: 'dwarven_smith',
      name: '地精鐵匠格魯姆',
      role: '流亡地精族的頂尖工匠',
      emoji: '🧙‍♂️',
      type: 'blacksmith',
      regionId: 'iron_mountain',
      x: 2420, y: 820,
      quests: [],
      dialog: {
        greeting: '（咿呀咿呀的說著半生不熟的漢話）你帶礦石，格魯姆幫你打！格魯姆最厲害！',
        shop_prompt: '看！這個！這個！格魯姆的傑作！稀世珍品！',
        after_quest: '謝謝朋友！格魯姆記著你！',
        lore: '格魯姆的族人原本住在山脈深處，卻被巨神驅逐。現在格魯姆一個人，很寂寞……',
      },
      merchandise: [
        { name: '玄鐵劍', price: 2000, type: 'weapon', icon: '🗡️', rarity: 'rare' },
        { name: '精鑄重甲', price: 2500, type: 'armor', icon: '🛡️', rarity: 'rare' },
        { name: '玄鐵強化石', price: 800, type: 'material', icon: '⚙️', rarity: 'uncommon' },
      ],
    },
    {
      id: 'spirit_medium',
      name: '靈媒蘇幽蘭',
      role: '能與亡靈溝通的靈媒師',
      emoji: '🔮',
      type: 'quest_giver',
      regionId: 'ghost_ruins',
      x: 3180, y: 1190,
      quests: ['q_soul_release', 'q_cursed_sword'],
      dialog: {
        greeting: '（輕輕顫抖）……好多怨靈……它們說……說有人類來了。你，你是來超度它們的嗎？',
        quest_hint: '若要讓亡靈安息，需要將它們的執念解開。首先，找到古城中的三個「怨靈燈」並點燃它們……',
        after_quest: '我感受到了……它們終於可以安息了……謝謝你，勇者。',
        lore: '我從小就能看見亡靈。幽冥古城的怨靈告訴我，它們其實並不想傷人，只是太過痛苦……',
      },
      merchandise: [],
    },
    {
      id: 'wandering_priest',
      name: '遊方道士清虛',
      role: '雲遊四海的道家修士',
      emoji: '⚗️',
      type: 'merchant',
      regionId: 'ghost_ruins',
      x: 3220, y: 1220,
      quests: ['q_lich_bane'],
      dialog: {
        greeting: '貧道清虛，雲遊至此，正巧遇到你這位有緣人。幽冥古城的魔君氣焰囂張，正需要勇者前往制伏！',
        shop_prompt: '貧道這裡有幾件鎮魔之物，對付邪祟最有效！',
        after_quest: '魔君已伏，幽冥古城終於重歸平靜。道家有言：道法自然，善惡自有其報！',
        lore: '貧道從青城山下來，奉師命遍歷天下，尋找阻止魔氣蔓延的方法。如今看來……事情比想象的嚴重得多。',
      },
      merchandise: [
        { name: '鎮魔符×3', price: 500, type: 'consumable', icon: '📜', rarity: 'uncommon' },
        { name: '驅邪香×5', price: 300, type: 'consumable', icon: '🕯️', rarity: 'common' },
        { name: '靈丹', price: 1500, type: 'consumable', icon: '💊', rarity: 'rare' },
      ],
    },
    {
      id: 'sect_master',
      name: '宗主劍無極',
      role: '青劍宗第十八代掌門',
      emoji: '🗡️',
      type: 'quest_giver',
      regionId: 'sect_headquarters',
      x: 2780, y: 390,
      quests: ['q_join_sect', 'q_inner_disciple', 'q_sect_mission'],
      dialog: {
        greeting: '（劍氣凌厲）外來之人，你的修為令老夫刮目相看。青劍宗向來不輕易收徒，但你……或許是個例外。',
        quest_hint: '若想加入本宗，先完成三項考驗。首先，前往翠玉仙境擊殺蛟王，帶回其「龍晶」……',
        after_quest: '很好。你已通過考驗，從今日起，你便是青劍宗的記名弟子！',
        lore: '青劍宗立派千年，宗規嚴苛卻公正。我們的祖師爺曾說：劍如人品，心正則劍正。如今宗門面臨危機，需要更多真正的劍士……',
      },
      merchandise: [],
    },
    {
      id: 'inner_elder',
      name: '長老司天明',
      role: '青劍宗修為最高的長老',
      emoji: '📿',
      type: 'trainer',
      regionId: 'sect_headquarters',
      x: 2820, y: 410,
      quests: [],
      dialog: {
        greeting: '年輕人，修行在於持之以恆。你有問題，老夫在此解答。',
        shop_prompt: '老夫可以傳授你幾門秘法，但需要你提供相應的修行資料……',
        after_quest: '融匯貫通，方得大道。繼續修行！',
        lore: '老夫修行八十年，曾十次挑戰飛升，均告失敗。如今明白，飛升非目的，修心才是根本……',
      },
      merchandise: [
        { name: '劍訣·上篇', price: 5000, type: 'skill_book', icon: '📖', rarity: 'rare' },
        { name: '心法·靜心訣', price: 3000, type: 'skill_book', icon: '📖', rarity: 'uncommon' },
      ],
    },
    {
      id: 'sect_steward',
      name: '管事王鐵柱',
      role: '青劍宗的內務管事',
      emoji: '📋',
      type: 'merchant',
      regionId: 'sect_headquarters',
      x: 2760, y: 420,
      quests: [],
      dialog: {
        greeting: '弟子，有什麼需要就告訴我！宗門的補給我都管著呢！',
        shop_prompt: '宗門福利，弟子享有八折優惠！',
        after_quest: '辦好了！有事再來找我！',
        lore: '（小聲說）宗主其實挺和藹的，就是臉太嚴肅……別告訴他我說這話。',
      },
      merchandise: [
        { name: '宗門丹藥×5', price: 100, type: 'consumable', icon: '💊', rarity: 'common' },
        { name: '宗門靈符', price: 200, type: 'consumable', icon: '📜', rarity: 'common' },
        { name: '宗門制服', price: 1000, type: 'armor', icon: '👘', rarity: 'uncommon' },
      ],
    },
    {
      id: 'training_instructor',
      name: '教習師兄趙猛',
      role: '宗門武術教習',
      emoji: '💪',
      type: 'trainer',
      regionId: 'sect_headquarters',
      x: 2840, y: 380,
      quests: [],
      dialog: {
        greeting: '師弟！來跟我練練？出劍要快、要准、要狠！',
        shop_prompt: '要提升實力，多練習才是硬道理！',
        after_quest: '哈哈！你小子有潛力！繼續加油！',
        lore: '我練了二十年基本劍法，剛開始覺得枯燥，後來才明白師父說的——基礎決定上限。那些花架子，在真正的高手面前一個照面就破了……',
      },
      merchandise: [],
    },
    {
      id: 'celestial_guardian',
      name: '仙山守衛飛鴻',
      role: '天極仙山的守護者',
      emoji: '🦅',
      type: 'quest_giver',
      regionId: 'heavenly_peak',
      x: 3980, y: 420,
      quests: ['q_ascend_peak', 'q_broken_seal'],
      dialog: {
        greeting: '（驚訝地）竟然有人能登上天極仙山……你的修為已達到凡界的頂峰。但前方的挑戰，比你想象的還要可怕。',
        quest_hint: '封印正在破裂。你必須先找到散落在山間的「三界仙紋石」，重新加固封印！',
        after_quest: '你做到了……但封印只是暫時加固。魔祖的力量在不斷增長，終有一天……勇者，做好準備。',
        lore: '我在這裡守衛了三千年。見過無數勇者前來試圖打破封印，也見過無數人為守護封印而犧牲……你是第一個讓我感到希望的人。',
      },
      merchandise: [],
    },
    {
      id: 'ancient_immortal',
      name: '古仙人無名氏',
      role: '萬年古仙，身份成謎',
      emoji: '👁️',
      type: 'merchant',
      regionId: 'heavenly_peak',
      x: 4020, y: 430,
      quests: ['q_demon_fragment'],
      dialog: {
        greeting: '……（沉默良久）……你來了。我已等待你一萬年。',
        shop_prompt: '我這裡有些東西，或許對你有用。不需要金幣——只需要你承諾，無論如何，都要守護這個世界。',
        after_quest: '……去吧。世界的命運，已系於你一身。我相信你。',
        lore: '我曾是魔祖的摯友，也是封印他的人之一。那一刻……我封印的不只是他，也封印了我自己的一部分……',
      },
      merchandise: [
        { name: '萬古靈符', price: 0, type: 'consumable', icon: '⭐', rarity: 'legendary' },
        { name: '古仙傳法石', price: 0, type: 'skill_book', icon: '💠', rarity: 'legendary' },
      ],
    },
    {
      id: 'plague_doctor',
      name: '神醫沈仁心',
      role: '流落血色沼澤的仁醫',
      emoji: '🩺',
      type: 'healer',
      regionId: 'blood_swamp',
      x: 1810, y: 1810,
      quests: ['q_swamp_cure'],
      dialog: {
        greeting: '（忙碌中抬頭）啊，終於有人來了！我一個人顧不過來這些中毒的難民……你能幫我嗎？',
        shop_prompt: '我這裡有解毒的藥品，請取用。金錢不重要，救人才是第一！',
        after_quest: '謝謝你帶來了解毒材料！有你這樣的英雄，世界還有希望……',
        lore: '我在這片沼澤紮根十年了。血毒太奇特，普通醫術無效。但我堅信，這世界上沒有治不好的病，只有還沒找到的方法……',
      },
      merchandise: [
        { name: '解毒丹×3', price: 400, type: 'consumable', icon: '💊', rarity: 'uncommon' },
        { name: '神醫藥草包', price: 800, type: 'consumable', icon: '🌿', rarity: 'uncommon' },
      ],
    },
    {
      id: 'lost_adventurer',
      name: '迷途冒險者小路',
      role: '在沼澤中迷路的年輕冒險者',
      emoji: '🗺️',
      type: 'misc',
      regionId: 'blood_swamp',
      x: 1850, y: 1850,
      quests: ['q_blood_lotus', 'q_drake_scale'],
      dialog: {
        greeting: '天啊……你是人嗎？！我已經在這裡迷路三天了！這鬼地方到處是血霧，完全看不清方向！',
        quest_hint: '哦對了，我迷路之前見過一朵血色蓮花，聽說有神奇的療效。你能幫我採幾朵嗎？另外……如果你能擊殺血蛟……',
        after_quest: '謝謝你！這裡有些東西是我找到的寶貝，你拿去！我要回家了！',
        lore: '我是從北方的幻仙城出發的……聽說沼澤深處有座沉沒的古廟，裡面有不知道多少寶物。結果……差點把命搭進去。',
      },
      merchandise: [],
    },
  ],

  // ============================================================
  // QUESTS
  // ============================================================
  quests: [
    {
      id: 'q_first_steps',
      name: '初出茅廬',
      giver: 'village_elder',
      type: 'main',
      levelReq: 1,
      description: '青雲長老請你在村莊附近練習，熟悉戰鬥技巧。',
      story: '青雲長老看出了你的潛力，希望你能成為守護村子的英雄。首先，讓我們從基礎開始……',
      objectives: [
        { type: 'kill', target: '妖狐', count: 5, current: 0, desc: '擊殺妖狐 0/5' },
        { type: 'kill', target: '幽靈武士', count: 3, current: 0, desc: '擊殺幽靈武士 0/3' },
      ],
      rewards: {
        exp: 500, gold: 200,
        items: [{ name: '初學者長劍', icon: '⚔️', rarity: 'common' }],
      },
      nextQuest: 'q_wolf_menace',
      completedDialog: '非常好！你有成為英雄的資質！',
    },
    {
      id: 'q_wolf_menace',
      name: '妖獸之禍',
      giver: 'village_elder',
      type: 'main',
      levelReq: 3,
      description: '村莊附近的妖獸最近愈發猖獗，長老請你剿滅其中的首領。',
      story: '自從白狐族長出現後，周邊的妖獸越來越膽大，甚至開始攻擊村民。必須找到族長，將其消滅！',
      objectives: [
        { type: 'kill_elite', target: '白狐族長', count: 1, current: 0, desc: '擊殺白狐族長 0/1' },
        { type: 'collect', target: '狐妖靈珠', count: 3, current: 0, desc: '收集狐妖靈珠 0/3' },
      ],
      rewards: {
        exp: 1500, gold: 600,
        items: [
          { name: '狐毛斗篷', icon: '🧣', rarity: 'uncommon' },
          { name: '回血丹×5', icon: '💊', rarity: 'common' },
        ],
      },
      nextQuest: null,
      completedDialog: '太好了！村民們可以暫時安心了，感謝你！',
    },
    {
      id: 'q_lost_herb',
      name: '失落的靈草',
      giver: 'quest_giver_chen',
      type: 'side',
      levelReq: 2,
      description: '陳英雄請你採集一些稀有草藥，用以救治染病的村民。',
      story: '村子裡有幾個老人染上了怪病，普通草藥毫無效果。陳英雄告訴你，在妖狐盤踞的林子裡有一種「翠心草」……',
      objectives: [
        { type: 'collect', target: '翠心草', count: 5, current: 0, desc: '採集翠心草 0/5' },
        { type: 'kill', target: '妖狐', count: 3, current: 0, desc: '擊殺守衛的妖狐 0/3' },
      ],
      rewards: {
        exp: 800, gold: 300,
        items: [{ name: '老兵護腕', icon: '🏺', rarity: 'uncommon' }],
      },
      nextQuest: null,
      completedDialog: '有了這些翠心草，老夫能救活那幾位老友了，謝謝你！',
    },
    {
      id: 'q_forest_curse',
      name: '翠竹詛咒',
      giver: 'hermit_zhang',
      type: 'main',
      levelReq: 12,
      description: '翠竹仙境被詛咒籠罩，隱士張無為請你尋找解咒材料。',
      story: '翠玉仙境的靈脈受到了蛟王詛咒的侵染，若不盡快解除，整片森林將化為死地。',
      objectives: [
        { type: 'collect', target: '翠玉靈晶', count: 3, current: 0, desc: '收集翠玉靈晶 0/3' },
        { type: 'kill', target: '火精靈', count: 8, current: 0, desc: '清除污染靈脈的火精靈 0/8' },
        { type: 'interact', target: '古靈脈石碑', count: 1, current: 0, desc: '激活靈脈石碑' },
      ],
      rewards: {
        exp: 5000, gold: 2000,
        items: [
          { name: '翠玉指環', icon: '💍', rarity: 'rare' },
          { name: '隱士秘法卷', icon: '📜', rarity: 'rare' },
        ],
      },
      nextQuest: 'q_jade_fragment',
      completedDialog: '靈脈的哭泣漸漸平息了……你做得很好，道友。',
    },
    {
      id: 'q_jade_fragment',
      name: '碎裂的靈玉',
      giver: 'hermit_zhang',
      type: 'main',
      levelReq: 15,
      description: '尋找散落在翠竹仙境中的上古靈玉碎片。',
      story: '靈脈石碑記載，昔日守護仙境的「天地靈玉」已被蛟王打碎，散落各處。只有重新聚合靈玉，才能根本解除詛咒。',
      objectives: [
        { type: 'collect', target: '靈玉碎片', count: 5, current: 0, desc: '收集靈玉碎片 0/5' },
        { type: 'kill_elite', target: '翠竹妖王', count: 2, current: 0, desc: '擊敗翠竹妖王 0/2' },
      ],
      rewards: {
        exp: 8000, gold: 3500,
        items: [
          { name: '天地靈玉（殘）', icon: '🔮', rarity: 'epic' },
          { name: '翠竹腰帶', icon: '🎋', rarity: 'rare' },
        ],
      },
      nextQuest: 'q_serpent_slayer',
      completedDialog: '靈玉重新凝聚了！現在，只剩下最後一步——必須消滅蛟王本身。',
    },
    {
      id: 'q_serpent_slayer',
      name: '蛟王討伐令',
      giver: 'forest_guard',
      type: 'boss',
      levelReq: 18,
      description: '前往翠竹祕境，擊殺翠玉蛟王。',
      story: '一切詛咒的根源——翠玉蛟王。這隻曾是仙境守護者的神靈，如今已墮入邪道。唯有解脫它，才能真正拯救仙境。',
      objectives: [
        { type: 'kill_boss', target: 'boss_jade_serpent', count: 1, current: 0, desc: '擊殺翠玉蛟王 0/1' },
        { type: 'collect', target: '靈晶核心', count: 1, current: 0, desc: '獲取靈晶核心 0/1' },
      ],
      rewards: {
        exp: 25000, gold: 10000,
        items: [
          { name: '翡翠玲瓏衣', icon: '🧥', rarity: 'epic' },
          { name: '蛟王之心', icon: '💚', rarity: 'epic' },
          { name: '翠竹宗門推薦信', icon: '📜', rarity: 'rare' },
        ],
      },
      nextQuest: null,
      completedDialog: '蛟王已安息……謝謝你解脫了它。翠竹仙境將重現昔日的繁盛，這一切因你而成！',
    },
    {
      id: 'q_ore_crisis',
      name: '礦場危機',
      giver: 'miner_foreman',
      type: 'side',
      levelReq: 26,
      description: '石魔族佔領了玄鐵礦場，清剿石魔並恢復生產。',
      story: '玄鐵礦場是整個地區的命脈，礦工們的生計全靠它。石魔族的突然入侵切斷了一切，必須找到原因並解決。',
      objectives: [
        { type: 'kill', target: '石魔', count: 15, current: 0, desc: '清除礦場石魔 0/15' },
        { type: 'collect', target: '玄鐵礦石', count: 20, current: 0, desc: '採集玄鐵礦石 0/20' },
        { type: 'kill_elite', target: '玄鐵巨魔', count: 1, current: 0, desc: '擊敗礦場頭目 0/1' },
      ],
      rewards: {
        exp: 12000, gold: 5000,
        items: [
          { name: '礦工頭盔', icon: '⛑️', rarity: 'uncommon' },
          { name: '玄鐵礦石×10', icon: '⚙️', rarity: 'common' },
        ],
      },
      nextQuest: 'q_titan_hunt',
      completedDialog: '礦場重開！工人們可以回來了！兄弟，你是我見過最厲害的外來者！',
    },
    {
      id: 'q_titan_hunt',
      name: '巨神獵手',
      giver: 'miner_foreman',
      type: 'boss',
      levelReq: 32,
      description: '深入玄鐵秘窟，挑戰並擊敗守護礦脈的玄鐵巨神。',
      story: '礦工們的探勘發現，石魔族之所以突然失控，是因為玄鐵巨神甦醒並向它們發出了召喚。巨神必須被制服！',
      objectives: [
        { type: 'kill_boss', target: 'boss_iron_titan', count: 1, current: 0, desc: '擊敗玄鐵巨神 0/1' },
        { type: 'collect', target: '巨神之心', count: 1, current: 0, desc: '獲取巨神之心 0/1' },
      ],
      rewards: {
        exp: 45000, gold: 18000,
        items: [
          { name: '玄鐵重甲', icon: '🛡️', rarity: 'epic' },
          { name: '破天長戟', icon: '🔱', rarity: 'epic' },
          { name: '礦脈守護戒', icon: '💍', rarity: 'rare' },
        ],
      },
      nextQuest: null,
      completedDialog: '難以置信！你真的做到了！巨神已臣服，礦脈從此無憂！',
    },
    {
      id: 'q_ancient_seal',
      name: '古老的封印',
      giver: 'dwarven_smith',
      type: 'side',
      levelReq: 28,
      description: '地精鐵匠格魯姆懷疑礦窟深處有上古封印，請你去調查。',
      story: '格魯姆在礦窟作業時，偶然發現了一扇奇特的石門，上面刻著格魯姆從未見過的符文。這扇門封印著什麼？',
      objectives: [
        { type: 'explore', target: '古封印地', count: 1, current: 0, desc: '調查古封印石門' },
        { type: 'collect', target: '古符文拓印', count: 3, current: 0, desc: '拓印古符文 0/3' },
      ],
      rewards: {
        exp: 8000, gold: 4000,
        items: [
          { name: '古符文手環', icon: '💠', rarity: 'rare' },
          { name: '格魯姆特製武器', icon: '🔨', rarity: 'rare' },
        ],
      },
      nextQuest: null,
      completedDialog: '這些符文……格魯姆認識！這是上古神祇的封印文！那扇門後面……可能有神的武器！',
    },
    {
      id: 'q_soul_release',
      name: '超度亡靈',
      giver: 'spirit_medium',
      type: 'main',
      levelReq: 42,
      description: '協助靈媒蘇幽蘭超度幽冥古城中的怨靈，讓它們得以安息。',
      story: '幽冥古城中有無數不甘心的怨靈，它們的執念讓它們無法離去。靈媒蘇幽蘭需要你幫她點燃三座「怨靈燈」，引導亡靈歸去。',
      objectives: [
        { type: 'interact', target: '怨靈燈', count: 3, current: 0, desc: '點燃怨靈燈 0/3' },
        { type: 'kill', target: '幽靈武士', count: 20, current: 0, desc: '超度怨靈 0/20' },
        { type: 'kill_elite', target: '陰靈將軍', count: 2, current: 0, desc: '超度陰靈將軍 0/2' },
      ],
      rewards: {
        exp: 20000, gold: 8000,
        items: [
          { name: '靈媒玉簫', icon: '🎶', rarity: 'rare' },
          { name: '超度符印', icon: '📜', rarity: 'uncommon' },
        ],
      },
      nextQuest: 'q_cursed_sword',
      completedDialog: '（淚流滿面）它們終於可以走了……謝謝你，真的謝謝你……',
    },
    {
      id: 'q_cursed_sword',
      name: '詛咒之劍',
      giver: 'spirit_medium',
      type: 'side',
      levelReq: 44,
      description: '幽冥古城中有一把帶有詛咒的古劍，必須找到並淨化它。',
      story: '怨靈告訴蘇幽蘭，古城被毀的根源在於一把「修羅血劍」——凝聚了屠城者怨恨的邪劍。它仍在古城某處封印……',
      objectives: [
        { type: 'explore', target: '修羅血劍所在', count: 1, current: 0, desc: '找到修羅血劍' },
        { type: 'kill_elite', target: '屍王術士', count: 3, current: 0, desc: '擊殺守衛詛咒劍的術士 0/3' },
        { type: 'interact', target: '淨化之火', count: 1, current: 0, desc: '以淨化之火解除詛咒' },
      ],
      rewards: {
        exp: 15000, gold: 6000,
        items: [
          { name: '淨化後的血劍', icon: '🗡️', rarity: 'epic' },
          { name: '古城紀念章', icon: '🏅', rarity: 'rare' },
        ],
      },
      nextQuest: 'q_lich_bane',
      completedDialog: '詛咒解除了！血劍重新散發出純淨的劍光……請你好好使用它吧。',
    },
    {
      id: 'q_lich_bane',
      name: '魔君討伐',
      giver: 'wandering_priest',
      type: 'boss',
      levelReq: 46,
      description: '進入冥府幽城，討伐千年死靈之主幽冥魔君。',
      story: '所有的怨靈、所有的詛咒，最終都指向同一個源頭——幽冥魔君。他是古城毀滅的真正罪魁禍首。唯有消滅他，才能讓這片土地徹底安息。',
      objectives: [
        { type: 'kill_boss', target: 'boss_lich_king', count: 1, current: 0, desc: '擊殺幽冥魔君 0/1' },
        { type: 'collect', target: '亡靈核心', count: 1, current: 0, desc: '獲取亡靈核心 0/1' },
      ],
      rewards: {
        exp: 80000, gold: 35000,
        items: [
          { name: '幽冥靈甲', icon: '🛡️', rarity: 'legendary' },
          { name: '判官巨筆', icon: '🖊️', rarity: 'legendary' },
          { name: '冥界通行令', icon: '📜', rarity: 'epic' },
        ],
      },
      nextQuest: null,
      completedDialog: '阿彌陀佛！（道士用錯了）……道法自然，善惡自有其報！幽冥古城終得安寧，道友大恩大德！',
    },
    {
      id: 'q_join_sect',
      name: '入宗考驗',
      giver: 'sect_master',
      type: 'main',
      levelReq: 15,
      description: '通過青劍宗的入門考驗，成為宗門弟子。',
      story: '青劍宗宗主劍無極看出了你的資質，提出讓你接受考驗。通過後，你將正式成為青劍宗的弟子！',
      objectives: [
        { type: 'kill_boss', target: 'boss_jade_serpent', count: 1, current: 0, desc: '擊殺蛟王（展示實力）0/1' },
        { type: 'collect', target: '龍晶', count: 1, current: 0, desc: '取回蛟王龍晶 0/1' },
        { type: 'visit', target: 'sect_headquarters', count: 1, current: 0, desc: '返回青劍宗' },
      ],
      rewards: {
        exp: 30000, gold: 5000,
        items: [
          { name: '青劍宗弟子令牌', icon: '🏅', rarity: 'rare' },
          { name: '宗門劍法入門', icon: '📖', rarity: 'rare' },
          { name: '宗門制服', icon: '👘', rarity: 'uncommon' },
        ],
      },
      nextQuest: 'q_inner_disciple',
      completedDialog: '很好。從今日起，你便是我青劍宗的記名弟子，切記嚴守宗規！',
    },
    {
      id: 'q_inner_disciple',
      name: '內門弟子考驗',
      giver: 'sect_master',
      type: 'main',
      levelReq: 35,
      description: '完成更艱難的考驗，晉升為青劍宗的內門弟子。',
      story: '宗主告訴你，若想成為內門弟子，必須完成一件幾乎不可能的任務——獨自進入玄鐵秘窟，討伐其中的巨神。',
      objectives: [
        { type: 'kill_boss', target: 'boss_iron_titan', count: 1, current: 0, desc: '擊敗玄鐵巨神 0/1' },
        { type: 'kill_boss', target: 'boss_lich_king', count: 1, current: 0, desc: '擊敗幽冥魔君 0/1' },
        { type: 'visit', target: 'sect_headquarters', count: 1, current: 0, desc: '返回宗門報告' },
      ],
      rewards: {
        exp: 100000, gold: 50000,
        items: [
          { name: '青劍宗內門令牌', icon: '💠', rarity: 'epic' },
          { name: '宗門秘法·劍氣訣', icon: '📖', rarity: 'epic' },
          { name: '翠劍', icon: '🗡️', rarity: 'epic' },
        ],
      },
      nextQuest: 'q_sect_mission',
      completedDialog: '（深深點頭）你已遠超普通弟子的實力。從此刻起，你是青劍宗的內門弟子！',
    },
    {
      id: 'q_sect_mission',
      name: '宗門緊急使命',
      giver: 'sect_master',
      type: 'main',
      levelReq: 55,
      description: '調查天極仙山的魔祖封印異常，這是宗門的最高機密任務。',
      story: '宗主緊急召見你，告知天極仙山的魔祖封印正在瓦解。若魔祖完全甦醒，三界將陷入混亂。你是宗門目前最強的弟子——這個任務非你莫屬！',
      objectives: [
        { type: 'visit', target: 'heavenly_peak', count: 1, current: 0, desc: '登上天極仙山' },
        { type: 'interact', target: '三界仙紋石', count: 3, current: 0, desc: '激活三界仙紋石 0/3' },
        { type: 'kill_boss', target: 'boss_demon_ancestor', count: 1, current: 0, desc: '對抗魔祖 0/1' },
      ],
      rewards: {
        exp: 500000, gold: 200000,
        items: [
          { name: '青劍宗首席弟子令', icon: '⭐', rarity: 'legendary' },
          { name: '封魔神劍', icon: '⚔️', rarity: 'legendary' },
          { name: '天極仙冊', icon: '📖', rarity: 'legendary' },
        ],
      },
      nextQuest: null,
      completedDialog: '……我等了太久了，終於等到了這樣的弟子。仙劍宗之名，將因你而永垂不朽。',
    },
    {
      id: 'q_swamp_cure',
      name: '沼澤的解藥',
      giver: 'plague_doctor',
      type: 'side',
      levelReq: 32,
      description: '協助神醫沈仁心採集解毒材料，救治沼澤中的難民。',
      story: '血色沼澤的毒瘴讓無數旅人中毒昏迷，神醫沈仁心一個人無力照應。你能幫他採集材料，配製大量解毒藥嗎？',
      objectives: [
        { type: 'collect', target: '血蓮花瓣', count: 8, current: 0, desc: '採集血蓮花瓣 0/8' },
        { type: 'collect', target: '淨化水晶', count: 5, current: 0, desc: '收集淨化水晶 0/5' },
        { type: 'kill', target: '妖狐', count: 10, current: 0, desc: '消滅帶毒妖獸 0/10' },
      ],
      rewards: {
        exp: 10000, gold: 4000,
        items: [
          { name: '神醫腰帶', icon: '💊', rarity: 'rare' },
          { name: '解毒丹×10', icon: '💊', rarity: 'uncommon' },
        ],
      },
      nextQuest: null,
      completedDialog: '太感謝了！有了這些材料，我可以救活至少五十個人！你真是菩薩派來的！',
    },
    {
      id: 'q_blood_lotus',
      name: '血色蓮花',
      giver: 'lost_adventurer',
      type: 'side',
      levelReq: 30,
      description: '在血色沼澤深處採集珍稀的血蓮花。',
      story: '傳說血色蓮花是極稀有的靈藥，在某些特殊條件下才能開放。冒險者小路偶然見過，卻沒能採集到。',
      objectives: [
        { type: 'collect', target: '血蓮花', count: 3, current: 0, desc: '採集血蓮花 0/3' },
      ],
      rewards: {
        exp: 6000, gold: 3000,
        items: [
          { name: '探險者地圖', icon: '🗺️', rarity: 'uncommon' },
          { name: '血蓮精華', icon: '🌸', rarity: 'rare' },
        ],
      },
      nextQuest: 'q_drake_scale',
      completedDialog: '太棒了！這朵花要是拿回去，能賣好多錢！不對，這麼珍貴的東西應該用作靈藥……',
    },
    {
      id: 'q_drake_scale',
      name: '血蛟鱗甲',
      giver: 'lost_adventurer',
      type: 'boss',
      levelReq: 38,
      description: '獵殺血蛟天魔，取得它身上的珍稀鱗甲。',
      story: '血蛟天魔的鱗甲是製作頂級防具的絕佳材料。它棲息在沉沒血祠的最深處，極難接近……',
      objectives: [
        { type: 'kill_boss', target: 'boss_blood_drake', count: 1, current: 0, desc: '擊殺血蛟天魔 0/1' },
        { type: 'collect', target: '血龍鱗', count: 5, current: 0, desc: '採集血龍鱗 0/5' },
      ],
      rewards: {
        exp: 60000, gold: 25000,
        items: [
          { name: '血龍鱗甲', icon: '🛡️', rarity: 'epic' },
          { name: '赤蠍毒針', icon: '🦂', rarity: 'rare' },
          { name: '探險者徽章', icon: '🏅', rarity: 'rare' },
        ],
      },
      nextQuest: null,
      completedDialog: '你真的殺掉血蛟了？！……我得回家了，江湖太危險了，不適合我這種普通人……',
    },
    {
      id: 'q_ascend_peak',
      name: '問鼎天極',
      giver: 'celestial_guardian',
      type: 'main',
      levelReq: 55,
      description: '協助仙山守衛飛鴻，尋找三塊仙紋石，加固封印。',
      story: '天極仙山封印的核心是三塊散落在山間的「三界仙紋石」。若封印徹底破裂，後果不堪設想……',
      objectives: [
        { type: 'collect', target: '三界仙紋石', count: 3, current: 0, desc: '收集三界仙紋石 0/3' },
        { type: 'kill_elite', target: '天雷神獸', count: 3, current: 0, desc: '擊退天雷神獸 0/3' },
        { type: 'kill_elite', target: '仙門衛士', count: 5, current: 0, desc: '清除叛變仙門衛士 0/5' },
      ],
      rewards: {
        exp: 120000, gold: 50000,
        items: [
          { name: '仙山令牌', icon: '🏅', rarity: 'epic' },
          { name: '三界護符', icon: '🔮', rarity: 'epic' },
        ],
      },
      nextQuest: 'q_broken_seal',
      completedDialog: '封印已暫時加固……但魔祖的力量在增長。我們的時間不多了。',
    },
    {
      id: 'q_broken_seal',
      name: '破碎的封印',
      giver: 'celestial_guardian',
      type: 'main',
      levelReq: 58,
      description: '調查封印破裂的根源，阻止局面進一步惡化。',
      story: '飛鴻告訴你，封印破裂並非自然現象，而是有人在故意破壞……這個人現在就在天極仙山中。',
      objectives: [
        { type: 'explore', target: '封印地核心', count: 1, current: 0, desc: '調查封印核心' },
        { type: 'kill_elite', target: '破封魔將', count: 5, current: 0, desc: '消滅破封魔將 0/5' },
        { type: 'interact', target: '封印修復台', count: 1, current: 0, desc: '嘗試修復封印' },
      ],
      rewards: {
        exp: 200000, gold: 80000,
        items: [
          { name: '仙尊遺甲（殘片）', icon: '🛡️', rarity: 'legendary' },
          { name: '天極通行令', icon: '📜', rarity: 'epic' },
        ],
      },
      nextQuest: 'q_demon_fragment',
      completedDialog: '（沉默良久）……封印無法完全修復了。魔祖的甦醒……恐怕已是定局。',
    },
    {
      id: 'q_demon_fragment',
      name: '魔祖碎片',
      giver: 'ancient_immortal',
      type: 'boss',
      levelReq: 63,
      description: '進入天穹封印地，面對魔祖降世，決定世界的命運。',
      story: '古仙人告訴你，他等待你一萬年，就是為了這一刻。魔祖必須被重新封印——或者……被徹底消滅。這個選擇將由你來做。',
      objectives: [
        { type: 'kill_boss', target: 'boss_demon_ancestor', count: 1, current: 0, desc: '對抗魔祖降世 0/1' },
        { type: 'interact', target: '萬古封印台', count: 1, current: 0, desc: '做出最終選擇' },
      ],
      rewards: {
        exp: 1000000, gold: 500000,
        items: [
          { name: '封魔神劍', icon: '⚔️', rarity: 'legendary' },
          { name: '仙尊遺甲', icon: '🛡️', rarity: 'legendary' },
          { name: '魔祖真炎（永久技能）', icon: '🔥', rarity: 'legendary' },
          { name: '三界英雄稱號', icon: '👑', rarity: 'legendary' },
        ],
      },
      nextQuest: null,
      completedDialog: '……（古仙人輕輕微笑）……我知道你能做到的。謝謝你，守護了這個世界……守護了我的罪過。',
    },
  ],

  // ============================================================
  // LORE STONES (Environmental Storytelling)
  // ============================================================
  loreStones: [
    {
      id: 'ls_01',
      regionId: 'starting_village',
      x: 350, y: 400,
      title: '青雲村由來記',
      text: '三千年前，仙人青雲子雲遊至此，見此地靈氣豐盈，遂設結界護佑。後人在此建村，取名「青雲」，以感念先人之恩。\n\n「身在雲中，心向天際。」——青雲子語錄',
      emoji: '📜',
    },
    {
      id: 'ls_02',
      regionId: 'jade_forest',
      x: 1200, y: 500,
      title: '翠玉仙境古碑',
      text: '此境昔為仙人靜修之所，竹影搖曳，靈泉湧現，千年之間無妖邪涉足。\n\n然靈脈衰竭，蛟王染指，昔日仙境今為妖域。願後來者能還此地清靜。',
      emoji: '🗿',
    },
    {
      id: 'ls_03',
      regionId: 'jade_forest',
      x: 1600, y: 700,
      title: '蛟王的傳說',
      text: '翠玉蛟王原為仙境守護神靈，以靈脈之氣為食。\n\n仙紀1203年，靈脈突然斷絕，蛟王饑渴之下失去理智，開始吞噬竹林中的靈獸……\n\n"我吃故我在。"——古籍記載的蛟王最後言語',
      emoji: '🐍',
    },
    {
      id: 'ls_04',
      regionId: 'iron_mountain',
      x: 2300, y: 750,
      title: '玄鐵山礦工誓言碑',
      text: '「玄鐵礦工公會誓言：\n凡我礦工，入山三不做：\n一不掘神聖之地，\n二不驚擾石魔族，\n三不貪圖深淵礦脈。\n違者逐出公會，永不錄用。」\n\n——公會會長周猛立',
      emoji: '⛏️',
    },
    {
      id: 'ls_05',
      regionId: 'iron_mountain',
      x: 2500, y: 850,
      title: '玄鐵巨神神話',
      text: '上古神話記載：山神以玄鐵鑄身，以火岩為心，守護山脈億萬年。每隔百年甦醒一次，巡視礦脈是否受到侵擾。\n\n然此次甦醒，巨神的眼中充滿了憤怒——礦工們破壞了它視為神聖的深層礦脈。',
      emoji: '🗻',
    },
    {
      id: 'ls_06',
      regionId: 'ghost_ruins',
      x: 3100, y: 1150,
      title: '幽冥古城興亡記',
      text: '幽冥古城建於仙紀800年，曾是東方最繁華的商業重鎮，人口逾五十萬。\n\n仙紀1187年，一夜之間，城中所有居民無故死亡，屍橫遍野。事後調查發現，一名術士在城下施展了禁忌的「修羅血煞大陣」……',
      emoji: '🏚️',
    },
    {
      id: 'ls_07',
      regionId: 'ghost_ruins',
      x: 3300, y: 1250,
      title: '魔君的自述',
      text: '「我叫做無名，曾是一個平凡的術士。\n我只想長生，只想知道死亡之後是什麼。\n我用盡了一生，換來了不死之身。\n現在我才明白——死亡才是真正的自由。」\n\n——幽冥魔君日記殘頁',
      emoji: '💀',
    },
    {
      id: 'ls_08',
      regionId: 'heavenly_peak',
      x: 3900, y: 420,
      title: '十二仙尊封印記',
      text: '仙紀元年，魔祖率萬魔大軍攻破三界屏障，仙魔大戰持續三百年。\n\n最終，十二仙尊以自身生命為代價，聯手施下「萬古封印術」，將魔祖鎖於天極仙山之顛。\n\n「封印者：青雲、白玉、赤炎……（後文模糊不清）」',
      emoji: '📖',
    },
    {
      id: 'ls_09',
      regionId: 'heavenly_peak',
      x: 4100, y: 460,
      title: '古仙人的囑托',
      text: '「若有人能看到這塊石碑，說明那一天終究來了。\n\n魔祖並非惡意，他只是被誤解了太久。\n若有機會，請試著……和他說話。\n\n也許戰鬥並非唯一的答案。」\n\n——一萬年前留下的刻痕',
      emoji: '👁️',
    },
    {
      id: 'ls_10',
      regionId: 'blood_swamp',
      x: 1750, y: 1750,
      title: '血色沼澤傳說',
      text: '「這片沼澤，原本是一片肥沃的農田。\n三千年前的一場大戰，百萬仙兵的鮮血染紅了土地，永遠無法恢復。\n\n那場戰爭的勝利者已遺忘了此地，但戰敗者的怨氣仍在沼澤中蔓延……」\n\n——旅行者手記',
      emoji: '🩸',
    },
    {
      id: 'ls_11',
      regionId: 'sect_headquarters',
      x: 2720, y: 380,
      title: '青劍宗宗訓',
      text: '【青劍宗宗訓】\n一、劍乃正義之器，不得用於欺凌弱小；\n二、修道者以慈悲為本，以公正為則；\n三、遇惡必誅，遇困必助；\n四、劍與心一體，心若不正，劍亦不利；\n五、宗門榮譽高於個人，共同守護仙道傳承。',
      emoji: '⚔️',
    },
    {
      id: 'ls_12',
      regionId: 'starting_village',
      x: 600, y: 440,
      title: '古井的傳說',
      text: '村口的古井建於三千年前，據說是青雲子仙人親手所鑿，井水含有微量靈氣，是村民長壽的秘密。\n\n也有人說，深夜在井邊靜聽，能聽到仙人的低語，為有緣人指點迷津……\n\n你試著俯身聆聽，卻只聽到了水波聲。',
      emoji: '🌀',
    },
  ],

  // ============================================================
  // MAP TELEPORT POINTS
  // ============================================================
  teleports: [
    { id: 'tp_village_to_forest', from: 'starting_village', to: 'jade_forest', x: 900, y: 500, label: '前往翠玉仙境→' },
    { id: 'tp_forest_to_mountain', from: 'jade_forest', to: 'iron_mountain', x: 2000, y: 600, label: '前往玄鐵山脈→' },
    { id: 'tp_mountain_to_ruins', from: 'iron_mountain', to: 'ghost_ruins', x: 3000, y: 1000, label: '前往幽冥古城→' },
    { id: 'tp_ruins_to_peak', from: 'ghost_ruins', to: 'heavenly_peak', x: 3800, y: 600, label: '前往天極仙山→' },
    { id: 'tp_village_to_swamp', from: 'starting_village', to: 'blood_swamp', x: 1300, y: 1200, label: '前往血色沼澤→' },
    { id: 'tp_mountain_to_sect', from: 'iron_mountain', to: 'sect_headquarters', x: 2600, y: 400, label: '前往青劍宗→' },
  ],

  // ============================================================
  // WORLD AUTO-CHAT MESSAGES (EXPANDED)
  // ============================================================
  worldChats: [
    { type: 'world', sender: '烈焰天尊', text: '【世界】翠竹祕境BOSS翠玉蛟王已討伐！首殺！' },
    { type: 'world', sender: '月影刺客', text: '【世界】幽冥魔君再次重生，有勇者敢挑戰嗎？' },
    { type: 'system', text: '【系統】血色沼澤血蛟天魔將在15分鐘後重生！' },
    { type: 'world', sender: '天劍孤雁', text: '【世界】玄鐵秘窟四層，求帶人！靈石報酬！' },
    { type: 'system', text: '【公告】本服首位達到60級的玩家為「烈焰天尊」！' },
    { type: 'world', sender: '白衣渡海', text: '【世界】青劍宗已開放，新人可加入！不拒任何等級！' },
    { type: 'npc', sender: '青雲長老', text: '老朽聽說魔祖的封印開始鬆動……願仙道護佑諸位英雄。' },
    { type: 'world', sender: '赤炎劍客', text: '【世界】天極仙山開放了！快去搶首通！' },
    { type: 'system', text: '【活動】本週雙倍掉落活動進行中，快來刷副本！' },
    { type: 'world', sender: '幽冥獵手', text: '【世界】收購亡靈核心×10，靈石1500一個，有貨聯繫！' },
    { type: 'npc', sender: '隱士張無為', text: '仙境詛咒漸漸消退……感謝諸位英雄的付出。' },
    { type: 'world', sender: '無情劍', text: '【世界】魔祖討伐隊招募中！需60級以上，要求有副本經驗！' },
    { type: 'system', text: '【世界BOSS】玄鐵巨神即將重生，坐標玄鐵山脈！' },
    { type: 'world', sender: '東方不敗', text: '【世界】哇，封魔神劍掉了！！！感謝RNG！！！' },
    { type: 'npc', sender: '宗主劍無極', text: '青劍宗招募有志之士，共抗魔道！欲加入者，到宗門大殿尋本座！' },
    { type: 'world', sender: '逍遙散人', text: '【世界】沉沒血祠路線攻略：一層左拐，二層注意毒地……' },
    { type: 'system', text: '【提示】使用傳送符可快速返回青雲村！' },
    { type: 'world', sender: '劍鬼無雙', text: '【世界】幽冥靈甲+判官巨筆，鎮壓lich！秒殺！' },
  ],
};
